# Generated by Django 4.0.2 on 2022-02-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auctions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctionbids', to='auctions.auction_listing'),
        ),
    ]
