# Generated by Django 4.0.2 on 2022-03-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_timestamp']},
        ),
    ]
