# Generated by Django 4.0.2 on 2022-03-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
    ]
